# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/conda/bin/cmake

# The command to remove a file.
RM = /opt/conda/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspaces/LCCNet/blender-mathutils

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspaces/LCCNet/blender-mathutils

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/conda/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/conda/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/conda/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/conda/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/conda/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/conda/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/conda/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/conda/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/LCCNet/blender-mathutils/CMakeFiles /workspaces/LCCNet/blender-mathutils//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/LCCNet/blender-mathutils/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named stubs_lib

# Build rule for target.
stubs_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stubs_lib
.PHONY : stubs_lib

# fast build rule for target.
stubs_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stubs_lib.dir/build.make CMakeFiles/stubs_lib.dir/build
.PHONY : stubs_lib/fast

#=============================================================================
# Target rules for targets named blenlib_lib

# Build rule for target.
blenlib_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 blenlib_lib
.PHONY : blenlib_lib

# fast build rule for target.
blenlib_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blenlib_lib.dir/build.make CMakeFiles/blenlib_lib.dir/build
.PHONY : blenlib_lib/fast

#=============================================================================
# Target rules for targets named mathutils_module

# Build rule for target.
mathutils_module: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mathutils_module
.PHONY : mathutils_module

# fast build rule for target.
mathutils_module/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mathutils_module.dir/build.make CMakeFiles/mathutils_module.dir/build
.PHONY : mathutils_module/fast

src/blenlib/intern/BLI_assert.o: src/blenlib/intern/BLI_assert.c.o
.PHONY : src/blenlib/intern/BLI_assert.o

# target to build an object file
src/blenlib/intern/BLI_assert.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blenlib_lib.dir/build.make CMakeFiles/blenlib_lib.dir/src/blenlib/intern/BLI_assert.c.o
.PHONY : src/blenlib/intern/BLI_assert.c.o

src/blenlib/intern/BLI_assert.i: src/blenlib/intern/BLI_assert.c.i
.PHONY : src/blenlib/intern/BLI_assert.i

# target to preprocess a source file
src/blenlib/intern/BLI_assert.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blenlib_lib.dir/build.make CMakeFiles/blenlib_lib.dir/src/blenlib/intern/BLI_assert.c.i
.PHONY : src/blenlib/intern/BLI_assert.c.i

src/blenlib/intern/BLI_assert.s: src/blenlib/intern/BLI_assert.c.s
.PHONY : src/blenlib/intern/BLI_assert.s

# target to generate assembly for a file
src/blenlib/intern/BLI_assert.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blenlib_lib.dir/build.make CMakeFiles/blenlib_lib.dir/src/blenlib/intern/BLI_assert.c.s
.PHONY : src/blenlib/intern/BLI_assert.c.s

src/blenlib/intern/math_base.o: src/blenlib/intern/math_base.c.o
.PHONY : src/blenlib/intern/math_base.o

# target to build an object file
src/blenlib/intern/math_base.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blenlib_lib.dir/build.make CMakeFiles/blenlib_lib.dir/src/blenlib/intern/math_base.c.o
.PHONY : src/blenlib/intern/math_base.c.o

src/blenlib/intern/math_base.i: src/blenlib/intern/math_base.c.i
.PHONY : src/blenlib/intern/math_base.i

# target to preprocess a source file
src/blenlib/intern/math_base.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blenlib_lib.dir/build.make CMakeFiles/blenlib_lib.dir/src/blenlib/intern/math_base.c.i
.PHONY : src/blenlib/intern/math_base.c.i

src/blenlib/intern/math_base.s: src/blenlib/intern/math_base.c.s
.PHONY : src/blenlib/intern/math_base.s

# target to generate assembly for a file
src/blenlib/intern/math_base.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blenlib_lib.dir/build.make CMakeFiles/blenlib_lib.dir/src/blenlib/intern/math_base.c.s
.PHONY : src/blenlib/intern/math_base.c.s

src/blenlib/intern/math_color.o: src/blenlib/intern/math_color.c.o
.PHONY : src/blenlib/intern/math_color.o

# target to build an object file
src/blenlib/intern/math_color.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blenlib_lib.dir/build.make CMakeFiles/blenlib_lib.dir/src/blenlib/intern/math_color.c.o
.PHONY : src/blenlib/intern/math_color.c.o

src/blenlib/intern/math_color.i: src/blenlib/intern/math_color.c.i
.PHONY : src/blenlib/intern/math_color.i

# target to preprocess a source file
src/blenlib/intern/math_color.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blenlib_lib.dir/build.make CMakeFiles/blenlib_lib.dir/src/blenlib/intern/math_color.c.i
.PHONY : src/blenlib/intern/math_color.c.i

src/blenlib/intern/math_color.s: src/blenlib/intern/math_color.c.s
.PHONY : src/blenlib/intern/math_color.s

# target to generate assembly for a file
src/blenlib/intern/math_color.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blenlib_lib.dir/build.make CMakeFiles/blenlib_lib.dir/src/blenlib/intern/math_color.c.s
.PHONY : src/blenlib/intern/math_color.c.s

src/blenlib/intern/math_geom.o: src/blenlib/intern/math_geom.c.o
.PHONY : src/blenlib/intern/math_geom.o

# target to build an object file
src/blenlib/intern/math_geom.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blenlib_lib.dir/build.make CMakeFiles/blenlib_lib.dir/src/blenlib/intern/math_geom.c.o
.PHONY : src/blenlib/intern/math_geom.c.o

src/blenlib/intern/math_geom.i: src/blenlib/intern/math_geom.c.i
.PHONY : src/blenlib/intern/math_geom.i

# target to preprocess a source file
src/blenlib/intern/math_geom.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blenlib_lib.dir/build.make CMakeFiles/blenlib_lib.dir/src/blenlib/intern/math_geom.c.i
.PHONY : src/blenlib/intern/math_geom.c.i

src/blenlib/intern/math_geom.s: src/blenlib/intern/math_geom.c.s
.PHONY : src/blenlib/intern/math_geom.s

# target to generate assembly for a file
src/blenlib/intern/math_geom.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blenlib_lib.dir/build.make CMakeFiles/blenlib_lib.dir/src/blenlib/intern/math_geom.c.s
.PHONY : src/blenlib/intern/math_geom.c.s

src/blenlib/intern/math_matrix.o: src/blenlib/intern/math_matrix.c.o
.PHONY : src/blenlib/intern/math_matrix.o

# target to build an object file
src/blenlib/intern/math_matrix.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blenlib_lib.dir/build.make CMakeFiles/blenlib_lib.dir/src/blenlib/intern/math_matrix.c.o
.PHONY : src/blenlib/intern/math_matrix.c.o

src/blenlib/intern/math_matrix.i: src/blenlib/intern/math_matrix.c.i
.PHONY : src/blenlib/intern/math_matrix.i

# target to preprocess a source file
src/blenlib/intern/math_matrix.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blenlib_lib.dir/build.make CMakeFiles/blenlib_lib.dir/src/blenlib/intern/math_matrix.c.i
.PHONY : src/blenlib/intern/math_matrix.c.i

src/blenlib/intern/math_matrix.s: src/blenlib/intern/math_matrix.c.s
.PHONY : src/blenlib/intern/math_matrix.s

# target to generate assembly for a file
src/blenlib/intern/math_matrix.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blenlib_lib.dir/build.make CMakeFiles/blenlib_lib.dir/src/blenlib/intern/math_matrix.c.s
.PHONY : src/blenlib/intern/math_matrix.c.s

src/blenlib/intern/math_rotation.o: src/blenlib/intern/math_rotation.c.o
.PHONY : src/blenlib/intern/math_rotation.o

# target to build an object file
src/blenlib/intern/math_rotation.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blenlib_lib.dir/build.make CMakeFiles/blenlib_lib.dir/src/blenlib/intern/math_rotation.c.o
.PHONY : src/blenlib/intern/math_rotation.c.o

src/blenlib/intern/math_rotation.i: src/blenlib/intern/math_rotation.c.i
.PHONY : src/blenlib/intern/math_rotation.i

# target to preprocess a source file
src/blenlib/intern/math_rotation.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blenlib_lib.dir/build.make CMakeFiles/blenlib_lib.dir/src/blenlib/intern/math_rotation.c.i
.PHONY : src/blenlib/intern/math_rotation.c.i

src/blenlib/intern/math_rotation.s: src/blenlib/intern/math_rotation.c.s
.PHONY : src/blenlib/intern/math_rotation.s

# target to generate assembly for a file
src/blenlib/intern/math_rotation.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blenlib_lib.dir/build.make CMakeFiles/blenlib_lib.dir/src/blenlib/intern/math_rotation.c.s
.PHONY : src/blenlib/intern/math_rotation.c.s

src/blenlib/intern/math_vector.o: src/blenlib/intern/math_vector.c.o
.PHONY : src/blenlib/intern/math_vector.o

# target to build an object file
src/blenlib/intern/math_vector.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blenlib_lib.dir/build.make CMakeFiles/blenlib_lib.dir/src/blenlib/intern/math_vector.c.o
.PHONY : src/blenlib/intern/math_vector.c.o

src/blenlib/intern/math_vector.i: src/blenlib/intern/math_vector.c.i
.PHONY : src/blenlib/intern/math_vector.i

# target to preprocess a source file
src/blenlib/intern/math_vector.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blenlib_lib.dir/build.make CMakeFiles/blenlib_lib.dir/src/blenlib/intern/math_vector.c.i
.PHONY : src/blenlib/intern/math_vector.c.i

src/blenlib/intern/math_vector.s: src/blenlib/intern/math_vector.c.s
.PHONY : src/blenlib/intern/math_vector.s

# target to generate assembly for a file
src/blenlib/intern/math_vector.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blenlib_lib.dir/build.make CMakeFiles/blenlib_lib.dir/src/blenlib/intern/math_vector.c.s
.PHONY : src/blenlib/intern/math_vector.c.s

src/generic/py_capi_utils.o: src/generic/py_capi_utils.c.o
.PHONY : src/generic/py_capi_utils.o

# target to build an object file
src/generic/py_capi_utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mathutils_module.dir/build.make CMakeFiles/mathutils_module.dir/src/generic/py_capi_utils.c.o
.PHONY : src/generic/py_capi_utils.c.o

src/generic/py_capi_utils.i: src/generic/py_capi_utils.c.i
.PHONY : src/generic/py_capi_utils.i

# target to preprocess a source file
src/generic/py_capi_utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mathutils_module.dir/build.make CMakeFiles/mathutils_module.dir/src/generic/py_capi_utils.c.i
.PHONY : src/generic/py_capi_utils.c.i

src/generic/py_capi_utils.s: src/generic/py_capi_utils.c.s
.PHONY : src/generic/py_capi_utils.s

# target to generate assembly for a file
src/generic/py_capi_utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mathutils_module.dir/build.make CMakeFiles/mathutils_module.dir/src/generic/py_capi_utils.c.s
.PHONY : src/generic/py_capi_utils.c.s

src/mathutils/mathutils.o: src/mathutils/mathutils.c.o
.PHONY : src/mathutils/mathutils.o

# target to build an object file
src/mathutils/mathutils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mathutils_module.dir/build.make CMakeFiles/mathutils_module.dir/src/mathutils/mathutils.c.o
.PHONY : src/mathutils/mathutils.c.o

src/mathutils/mathutils.i: src/mathutils/mathutils.c.i
.PHONY : src/mathutils/mathutils.i

# target to preprocess a source file
src/mathutils/mathutils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mathutils_module.dir/build.make CMakeFiles/mathutils_module.dir/src/mathutils/mathutils.c.i
.PHONY : src/mathutils/mathutils.c.i

src/mathutils/mathutils.s: src/mathutils/mathutils.c.s
.PHONY : src/mathutils/mathutils.s

# target to generate assembly for a file
src/mathutils/mathutils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mathutils_module.dir/build.make CMakeFiles/mathutils_module.dir/src/mathutils/mathutils.c.s
.PHONY : src/mathutils/mathutils.c.s

src/mathutils/mathutils_Color.o: src/mathutils/mathutils_Color.c.o
.PHONY : src/mathutils/mathutils_Color.o

# target to build an object file
src/mathutils/mathutils_Color.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mathutils_module.dir/build.make CMakeFiles/mathutils_module.dir/src/mathutils/mathutils_Color.c.o
.PHONY : src/mathutils/mathutils_Color.c.o

src/mathutils/mathutils_Color.i: src/mathutils/mathutils_Color.c.i
.PHONY : src/mathutils/mathutils_Color.i

# target to preprocess a source file
src/mathutils/mathutils_Color.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mathutils_module.dir/build.make CMakeFiles/mathutils_module.dir/src/mathutils/mathutils_Color.c.i
.PHONY : src/mathutils/mathutils_Color.c.i

src/mathutils/mathutils_Color.s: src/mathutils/mathutils_Color.c.s
.PHONY : src/mathutils/mathutils_Color.s

# target to generate assembly for a file
src/mathutils/mathutils_Color.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mathutils_module.dir/build.make CMakeFiles/mathutils_module.dir/src/mathutils/mathutils_Color.c.s
.PHONY : src/mathutils/mathutils_Color.c.s

src/mathutils/mathutils_Euler.o: src/mathutils/mathutils_Euler.c.o
.PHONY : src/mathutils/mathutils_Euler.o

# target to build an object file
src/mathutils/mathutils_Euler.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mathutils_module.dir/build.make CMakeFiles/mathutils_module.dir/src/mathutils/mathutils_Euler.c.o
.PHONY : src/mathutils/mathutils_Euler.c.o

src/mathutils/mathutils_Euler.i: src/mathutils/mathutils_Euler.c.i
.PHONY : src/mathutils/mathutils_Euler.i

# target to preprocess a source file
src/mathutils/mathutils_Euler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mathutils_module.dir/build.make CMakeFiles/mathutils_module.dir/src/mathutils/mathutils_Euler.c.i
.PHONY : src/mathutils/mathutils_Euler.c.i

src/mathutils/mathutils_Euler.s: src/mathutils/mathutils_Euler.c.s
.PHONY : src/mathutils/mathutils_Euler.s

# target to generate assembly for a file
src/mathutils/mathutils_Euler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mathutils_module.dir/build.make CMakeFiles/mathutils_module.dir/src/mathutils/mathutils_Euler.c.s
.PHONY : src/mathutils/mathutils_Euler.c.s

src/mathutils/mathutils_Matrix.o: src/mathutils/mathutils_Matrix.c.o
.PHONY : src/mathutils/mathutils_Matrix.o

# target to build an object file
src/mathutils/mathutils_Matrix.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mathutils_module.dir/build.make CMakeFiles/mathutils_module.dir/src/mathutils/mathutils_Matrix.c.o
.PHONY : src/mathutils/mathutils_Matrix.c.o

src/mathutils/mathutils_Matrix.i: src/mathutils/mathutils_Matrix.c.i
.PHONY : src/mathutils/mathutils_Matrix.i

# target to preprocess a source file
src/mathutils/mathutils_Matrix.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mathutils_module.dir/build.make CMakeFiles/mathutils_module.dir/src/mathutils/mathutils_Matrix.c.i
.PHONY : src/mathutils/mathutils_Matrix.c.i

src/mathutils/mathutils_Matrix.s: src/mathutils/mathutils_Matrix.c.s
.PHONY : src/mathutils/mathutils_Matrix.s

# target to generate assembly for a file
src/mathutils/mathutils_Matrix.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mathutils_module.dir/build.make CMakeFiles/mathutils_module.dir/src/mathutils/mathutils_Matrix.c.s
.PHONY : src/mathutils/mathutils_Matrix.c.s

src/mathutils/mathutils_Quaternion.o: src/mathutils/mathutils_Quaternion.c.o
.PHONY : src/mathutils/mathutils_Quaternion.o

# target to build an object file
src/mathutils/mathutils_Quaternion.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mathutils_module.dir/build.make CMakeFiles/mathutils_module.dir/src/mathutils/mathutils_Quaternion.c.o
.PHONY : src/mathutils/mathutils_Quaternion.c.o

src/mathutils/mathutils_Quaternion.i: src/mathutils/mathutils_Quaternion.c.i
.PHONY : src/mathutils/mathutils_Quaternion.i

# target to preprocess a source file
src/mathutils/mathutils_Quaternion.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mathutils_module.dir/build.make CMakeFiles/mathutils_module.dir/src/mathutils/mathutils_Quaternion.c.i
.PHONY : src/mathutils/mathutils_Quaternion.c.i

src/mathutils/mathutils_Quaternion.s: src/mathutils/mathutils_Quaternion.c.s
.PHONY : src/mathutils/mathutils_Quaternion.s

# target to generate assembly for a file
src/mathutils/mathutils_Quaternion.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mathutils_module.dir/build.make CMakeFiles/mathutils_module.dir/src/mathutils/mathutils_Quaternion.c.s
.PHONY : src/mathutils/mathutils_Quaternion.c.s

src/mathutils/mathutils_Vector.o: src/mathutils/mathutils_Vector.c.o
.PHONY : src/mathutils/mathutils_Vector.o

# target to build an object file
src/mathutils/mathutils_Vector.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mathutils_module.dir/build.make CMakeFiles/mathutils_module.dir/src/mathutils/mathutils_Vector.c.o
.PHONY : src/mathutils/mathutils_Vector.c.o

src/mathutils/mathutils_Vector.i: src/mathutils/mathutils_Vector.c.i
.PHONY : src/mathutils/mathutils_Vector.i

# target to preprocess a source file
src/mathutils/mathutils_Vector.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mathutils_module.dir/build.make CMakeFiles/mathutils_module.dir/src/mathutils/mathutils_Vector.c.i
.PHONY : src/mathutils/mathutils_Vector.c.i

src/mathutils/mathutils_Vector.s: src/mathutils/mathutils_Vector.c.s
.PHONY : src/mathutils/mathutils_Vector.s

# target to generate assembly for a file
src/mathutils/mathutils_Vector.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mathutils_module.dir/build.make CMakeFiles/mathutils_module.dir/src/mathutils/mathutils_Vector.c.s
.PHONY : src/mathutils/mathutils_Vector.c.s

src/mathutils/mathutils_geometry.o: src/mathutils/mathutils_geometry.c.o
.PHONY : src/mathutils/mathutils_geometry.o

# target to build an object file
src/mathutils/mathutils_geometry.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mathutils_module.dir/build.make CMakeFiles/mathutils_module.dir/src/mathutils/mathutils_geometry.c.o
.PHONY : src/mathutils/mathutils_geometry.c.o

src/mathutils/mathutils_geometry.i: src/mathutils/mathutils_geometry.c.i
.PHONY : src/mathutils/mathutils_geometry.i

# target to preprocess a source file
src/mathutils/mathutils_geometry.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mathutils_module.dir/build.make CMakeFiles/mathutils_module.dir/src/mathutils/mathutils_geometry.c.i
.PHONY : src/mathutils/mathutils_geometry.c.i

src/mathutils/mathutils_geometry.s: src/mathutils/mathutils_geometry.c.s
.PHONY : src/mathutils/mathutils_geometry.s

# target to generate assembly for a file
src/mathutils/mathutils_geometry.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mathutils_module.dir/build.make CMakeFiles/mathutils_module.dir/src/mathutils/mathutils_geometry.c.s
.PHONY : src/mathutils/mathutils_geometry.c.s

src/mathutils/mathutils_interpolate.o: src/mathutils/mathutils_interpolate.c.o
.PHONY : src/mathutils/mathutils_interpolate.o

# target to build an object file
src/mathutils/mathutils_interpolate.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mathutils_module.dir/build.make CMakeFiles/mathutils_module.dir/src/mathutils/mathutils_interpolate.c.o
.PHONY : src/mathutils/mathutils_interpolate.c.o

src/mathutils/mathutils_interpolate.i: src/mathutils/mathutils_interpolate.c.i
.PHONY : src/mathutils/mathutils_interpolate.i

# target to preprocess a source file
src/mathutils/mathutils_interpolate.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mathutils_module.dir/build.make CMakeFiles/mathutils_module.dir/src/mathutils/mathutils_interpolate.c.i
.PHONY : src/mathutils/mathutils_interpolate.c.i

src/mathutils/mathutils_interpolate.s: src/mathutils/mathutils_interpolate.c.s
.PHONY : src/mathutils/mathutils_interpolate.s

# target to generate assembly for a file
src/mathutils/mathutils_interpolate.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mathutils_module.dir/build.make CMakeFiles/mathutils_module.dir/src/mathutils/mathutils_interpolate.c.s
.PHONY : src/mathutils/mathutils_interpolate.c.s

src/stubs/stubs.o: src/stubs/stubs.c.o
.PHONY : src/stubs/stubs.o

# target to build an object file
src/stubs/stubs.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stubs_lib.dir/build.make CMakeFiles/stubs_lib.dir/src/stubs/stubs.c.o
.PHONY : src/stubs/stubs.c.o

src/stubs/stubs.i: src/stubs/stubs.c.i
.PHONY : src/stubs/stubs.i

# target to preprocess a source file
src/stubs/stubs.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stubs_lib.dir/build.make CMakeFiles/stubs_lib.dir/src/stubs/stubs.c.i
.PHONY : src/stubs/stubs.c.i

src/stubs/stubs.s: src/stubs/stubs.c.s
.PHONY : src/stubs/stubs.s

# target to generate assembly for a file
src/stubs/stubs.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stubs_lib.dir/build.make CMakeFiles/stubs_lib.dir/src/stubs/stubs.c.s
.PHONY : src/stubs/stubs.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... blenlib_lib"
	@echo "... mathutils_module"
	@echo "... stubs_lib"
	@echo "... src/blenlib/intern/BLI_assert.o"
	@echo "... src/blenlib/intern/BLI_assert.i"
	@echo "... src/blenlib/intern/BLI_assert.s"
	@echo "... src/blenlib/intern/math_base.o"
	@echo "... src/blenlib/intern/math_base.i"
	@echo "... src/blenlib/intern/math_base.s"
	@echo "... src/blenlib/intern/math_color.o"
	@echo "... src/blenlib/intern/math_color.i"
	@echo "... src/blenlib/intern/math_color.s"
	@echo "... src/blenlib/intern/math_geom.o"
	@echo "... src/blenlib/intern/math_geom.i"
	@echo "... src/blenlib/intern/math_geom.s"
	@echo "... src/blenlib/intern/math_matrix.o"
	@echo "... src/blenlib/intern/math_matrix.i"
	@echo "... src/blenlib/intern/math_matrix.s"
	@echo "... src/blenlib/intern/math_rotation.o"
	@echo "... src/blenlib/intern/math_rotation.i"
	@echo "... src/blenlib/intern/math_rotation.s"
	@echo "... src/blenlib/intern/math_vector.o"
	@echo "... src/blenlib/intern/math_vector.i"
	@echo "... src/blenlib/intern/math_vector.s"
	@echo "... src/generic/py_capi_utils.o"
	@echo "... src/generic/py_capi_utils.i"
	@echo "... src/generic/py_capi_utils.s"
	@echo "... src/mathutils/mathutils.o"
	@echo "... src/mathutils/mathutils.i"
	@echo "... src/mathutils/mathutils.s"
	@echo "... src/mathutils/mathutils_Color.o"
	@echo "... src/mathutils/mathutils_Color.i"
	@echo "... src/mathutils/mathutils_Color.s"
	@echo "... src/mathutils/mathutils_Euler.o"
	@echo "... src/mathutils/mathutils_Euler.i"
	@echo "... src/mathutils/mathutils_Euler.s"
	@echo "... src/mathutils/mathutils_Matrix.o"
	@echo "... src/mathutils/mathutils_Matrix.i"
	@echo "... src/mathutils/mathutils_Matrix.s"
	@echo "... src/mathutils/mathutils_Quaternion.o"
	@echo "... src/mathutils/mathutils_Quaternion.i"
	@echo "... src/mathutils/mathutils_Quaternion.s"
	@echo "... src/mathutils/mathutils_Vector.o"
	@echo "... src/mathutils/mathutils_Vector.i"
	@echo "... src/mathutils/mathutils_Vector.s"
	@echo "... src/mathutils/mathutils_geometry.o"
	@echo "... src/mathutils/mathutils_geometry.i"
	@echo "... src/mathutils/mathutils_geometry.s"
	@echo "... src/mathutils/mathutils_interpolate.o"
	@echo "... src/mathutils/mathutils_interpolate.i"
	@echo "... src/mathutils/mathutils_interpolate.s"
	@echo "... src/stubs/stubs.o"
	@echo "... src/stubs/stubs.i"
	@echo "... src/stubs/stubs.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

